spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: 'jdbc:mysql://localhost:3306/rehear?useUnicode=true&serverTimezone=Asia/Seoul'
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
jwt:
  secret: